name: flutter_translate
description: "Flutter translate"
version: 0.0.2
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.3
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: